# Generated by Django 5.2.15 on 2026-06-15 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('backup', 'Backup'), ('restore', 'Restauração')], max_length=10)),
                ('arquivo', models.FileField(blank=True, upload_to='backups/')),
                ('observacao', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'log de backup',
                'verbose_name_plural': 'logs de backup',
                'ordering': ['-data_hora'],
            },
        ),
    ]
