# Generated by Django 5.2.15 on 2026-06-15 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaRetorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_contato', models.DateField()),
                ('data_alerta', models.DateField()),
                ('dispensado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_retorno', to='clientes.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_retorno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'alerta de retorno',
                'verbose_name_plural': 'alertas de retorno',
                'ordering': ['data_alerta'],
            },
        ),
        migrations.CreateModel(
            name='NotaRelacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('texto', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_relacionamento', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'nota de relacionamento',
                'verbose_name_plural': 'notas de relacionamento',
                'ordering': ['-data'],
                'unique_together': {('cliente', 'data')},
            },
        ),
    ]
