# Generated by Django 5.2.15 on 2026-06-15 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('produtos_texto', models.CharField(blank=True, max_length=500)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='clientes.cliente')),
                ('produtos', models.ManyToManyField(blank=True, to='clientes.produto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'venda',
                'verbose_name_plural': 'vendas',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('ano', models.PositiveSmallIntegerField()),
                ('meta_contatos', models.PositiveIntegerField(default=60)),
                ('meta_vendas', models.DecimalField(decimal_places=2, default=80000, max_digits=12)),
                ('vendedor', models.ForeignKey(blank=True, help_text='Vazio = meta geral da equipe', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metas_mensais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'meta mensal',
                'verbose_name_plural': 'metas mensais',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('vendedor', 'mes', 'ano')},
            },
        ),
    ]
