# Generated by Django 5.2.15 on 2026-06-16 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metamensal',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='metamensal',
            name='meta_clientes_novos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metamensal',
            name='meta_propostas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metamensal',
            name='meta_visitas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metamensal',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ConquistaVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('primeira_venda', 'Primeira Venda'), ('cem_contatos', '100 Contatos'), ('meta_batida', 'Meta Batida'), ('top_mes', 'Top do Mês'), ('maior_crescimento', 'Maior Crescimento')], max_length=30)),
                ('mes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ano', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('data_conquista', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conquista',
                'verbose_name_plural': 'conquistas',
                'ordering': ['-data_conquista'],
                'unique_together': {('usuario', 'tipo', 'mes', 'ano')},
            },
        ),
    ]
