# Generated by Django 6.0.6 on 2026-06-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0002_metas_produtividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conquistavendedor',
            name='tipo',
            field=models.CharField(choices=[('primeira_venda', 'Primeira Venda'), ('cem_contatos', '100 Contatos'), ('meta_batida', 'Meta Batida'), ('top_mes', 'Top do Mês'), ('maior_crescimento', 'Maior Crescimento'), ('rei_whatsapp', 'Rei do WhatsApp'), ('mestre_followup', 'Mestre do Follow-up'), ('streak_meta_7', '7 Dias de Meta')], max_length=30),
        ),
    ]
