# Generated by Django 6.0.6 on 2026-06-24 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0003_motivo_perda_powerup'),
        ('relacionamento', '0005_atividadeclienteedicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='atividade_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_geradas', to='relacionamento.atividadecliente'),
        ),
    ]
