# Generated by Django 5.2.15 on 2026-06-15 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome_livre', models.CharField(blank=True, help_text='Nome livre quando cliente não está cadastrado', max_length=255)),
                ('data', models.DateField()),
                ('resultado', models.CharField(choices=[('contato', 'Contato'), ('venda', 'Venda'), ('sem_resposta', 'Sem resposta'), ('retorno', 'Retorno'), ('proposta', 'Proposta'), ('obs', 'Observação')], max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_diarios', to='clientes.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_diarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro diário',
                'verbose_name_plural': 'registros diários',
                'ordering': ['-data', '-created_at'],
            },
        ),
    ]
