# Generated by Django 5.2.15 on 2026-06-16 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


TIPO_MAP = {
    'contato': 'LIGACAO',
    'retorno': 'LIGACAO',
    'proposta': 'PROPOSTA',
    'venda': 'POS_VENDA',
    'sem_resposta': 'OUTRO',
    'obs': 'OUTRO',
}

RESULTADO_MAP = {
    'venda': 'PEDIDO_FECHADO',
    'proposta': 'PROPOSTA_ENVIADA',
    'retorno': 'AGUARDANDO_RETORNO',
    'sem_resposta': 'PENDENTE',
    'contato': 'INTERESSADO',
    'obs': 'PENDENTE',
}


def migrar_dados_legados(apps, schema_editor):
    AtividadeCliente = apps.get_model('relacionamento', 'AtividadeCliente')
    HistoricoInteracao = apps.get_model('clientes', 'HistoricoInteracao')
    AlertaRetorno = apps.get_model('calendario', 'AlertaRetorno')

    for hi in HistoricoInteracao.objects.select_related('cliente', 'vendedor').prefetch_related('produtos').all():
        tipo = TIPO_MAP.get(hi.tipo, 'OUTRO')
        resultado = RESULTADO_MAP.get(hi.tipo, 'PENDENTE')
        produto = hi.produtos.first()
        data_criacao = hi.created_at
        if not data_criacao:
            from datetime import datetime
            data_criacao = timezone.make_aware(
                datetime.combine(hi.data, datetime.min.time())
            )
        AtividadeCliente.objects.create(
            cliente_id=hi.cliente_id,
            usuario_id=hi.vendedor_id,
            tipo_contato=tipo,
            assunto='',
            resumo=hi.observacao or f'Migrado: {hi.tipo}',
            resultado=resultado,
            produto_relacionado_id=produto.pk if produto else None,
            proxima_acao='SEM_ACAO',
            concluida=True,
            data_criacao=data_criacao,
            data_atualizacao=data_criacao,
        )

    for alerta in AlertaRetorno.objects.filter(dispensado=False).select_related('cliente', 'vendedor'):
        AtividadeCliente.objects.create(
            cliente_id=alerta.cliente_id,
            usuario_id=alerta.vendedor_id,
            tipo_contato='LIGACAO',
            assunto='Follow-up',
            resumo='Follow-up migrado do alerta de retorno.',
            resultado='PENDENTE',
            proxima_acao='LIGAR',
            data_proxima_acao=alerta.data_alerta,
            concluida=False,
            data_criacao=alerta.created_at or timezone.now(),
            data_atualizacao=alerta.created_at or timezone.now(),
        )


def reverse_migrar(apps, schema_editor):
    AtividadeCliente = apps.get_model('relacionamento', 'AtividadeCliente')
    AtividadeCliente.objects.all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendario', '0001_initial'),
        ('clientes', '0004_categoria_inativo_produtos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contato', models.CharField(choices=[('LIGACAO', 'Ligação'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'E-mail'), ('VISITA', 'Visita'), ('REUNIAO', 'Reunião'), ('NEGOCIACAO', 'Negociação'), ('PROPOSTA', 'Proposta'), ('POS_VENDA', 'Pós-venda'), ('RECLAMACAO', 'Reclamação'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('assunto', models.CharField(blank=True, max_length=255)),
                ('resumo', models.TextField()),
                ('resultado', models.CharField(choices=[('SEM_INTERESSE', 'Sem interesse'), ('INTERESSADO', 'Interessado'), ('PROPOSTA_ENVIADA', 'Proposta enviada'), ('AGUARDANDO_RETORNO', 'Aguardando retorno'), ('PEDIDO_FECHADO', 'Pedido fechado'), ('POS_VENDA', 'Pós-venda'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=30)),
                ('humor_cliente', models.CharField(blank=True, choices=[('MUITO_RECEPTIVO', 'Muito receptivo'), ('RECEPTIVO', 'Receptivo'), ('NEUTRO', 'Neutro'), ('RESISTENTE', 'Resistente'), ('INSATISFEITO', 'Insatisfeito')], max_length=20, null=True)),
                ('proxima_acao', models.CharField(choices=[('LIGAR', 'Ligar'), ('ENVIAR_CATALOGO', 'Enviar catálogo'), ('ENVIAR_PROPOSTA', 'Enviar proposta'), ('AGENDAR_VISITA', 'Agendar visita'), ('ENVIAR_WHATSAPP', 'Enviar WhatsApp'), ('ENVIAR_EMAIL', 'Enviar e-mail'), ('SEM_ACAO', 'Sem ação')], default='SEM_ACAO', max_length=30)),
                ('data_proxima_acao', models.DateField(blank=True, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='clientes.cliente')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_excluidas', to=settings.AUTH_USER_MODEL)),
                ('produto_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to='clientes.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades_cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'atividade do cliente',
                'verbose_name_plural': 'atividades do cliente',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.RunPython(migrar_dados_legados, reverse_migrar),
    ]
