# Generated by Django 5.2.15 on 2026-06-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadecliente',
            name='hora_proxima_acao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atividadecliente',
            name='proxima_acao',
            field=models.CharField(choices=[('LIGAR', 'Ligar'), ('ENVIAR_CATALOGO', 'Enviar catálogo'), ('ENVIAR_PROPOSTA', 'Enviar proposta'), ('AGENDAR_VISITA', 'Agendar visita'), ('ENVIAR_WHATSAPP', 'Enviar WhatsApp'), ('ENVIAR_EMAIL', 'Enviar e-mail'), ('SEM_ACAO', 'Encerrar atendimento')], default='SEM_ACAO', max_length=30),
        ),
        migrations.AlterField(
            model_name='atividadecliente',
            name='resultado',
            field=models.CharField(choices=[('SEM_RESPOSTA', 'Sem resposta'), ('CONTATO_REALIZADO', 'Contato realizado'), ('SEM_INTERESSE', 'Sem interesse'), ('INTERESSADO', 'Interessado'), ('PROPOSTA_ENVIADA', 'Proposta enviada'), ('AGUARDANDO_RETORNO', 'Aguardando retorno'), ('PEDIDO_FECHADO', 'Pedido fechado'), ('POS_VENDA', 'Pós-venda'), ('PENDENTE', 'Sem resposta')], default='PENDENTE', max_length=30),
        ),
    ]
