# Generated by Django 5.2.15 on 2026-06-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamento', '0003_multiusuario_fase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadecliente',
            name='valor_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor da venda'),
        ),
    ]
