# Generated by Django 6.0.6 on 2026-06-24 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamento', '0004_valor_venda_atividade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeClienteEdicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alteracoes', models.JSONField(default=list)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edicoes', to='relacionamento.atividadecliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edicoes_atividade', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'edição de atividade',
                'verbose_name_plural': 'edições de atividade',
                'ordering': ['-criado_em'],
            },
        ),
    ]
