# Generated by Django 5.2.15 on 2026-06-15 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('novo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('ativo', 'Ativo'), ('adormecido', 'Adormecido'), ('prospeccao', 'Prospecção')], default='ativo', max_length=20)),
                ('nome', models.CharField(max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('telefone', models.CharField(blank=True, max_length=50)),
                ('responsavel', models.CharField(blank=True, max_length=150)),
                ('instagram', models.URLField(blank=True)),
                ('endereco', models.TextField(blank=True)),
                ('data_primeiro_contato', models.DateField(blank=True, null=True)),
                ('feedback_original', models.TextField(blank=True)),
                ('ativo_no_sistema', models.BooleanField(default=True)),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to=settings.AUTH_USER_MODEL)),
                ('produtos_exclusivos', models.ManyToManyField(blank=True, related_name='clientes_exclusivos', to='clientes.produto')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoInteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('venda', 'Venda'), ('contato', 'Contato'), ('retorno', 'Retorno'), ('proposta', 'Proposta'), ('sem_resposta', 'Sem resposta'), ('obs', 'Observação')], max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='clientes.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interacoes', to=settings.AUTH_USER_MODEL)),
                ('produtos', models.ManyToManyField(blank=True, to='clientes.produto')),
            ],
            options={
                'verbose_name': 'histórico de interação',
                'verbose_name_plural': 'históricos de interação',
                'ordering': ['-data', '-created_at'],
            },
        ),
    ]
