# Generated by Django 5.2.15 on 2026-06-16 10:54

from django.db import migrations, models


def normalizar_instagram_existente(apps, schema_editor):
    Cliente = apps.get_model('clientes', 'Cliente')
    from clientes.utils import normalizar_instagram

    for cliente in Cliente.objects.exclude(instagram='').iterator():
        username = normalizar_instagram(cliente.instagram)
        if username != cliente.instagram:
            cliente.instagram = username
            cliente.save(update_fields=['instagram'])


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='cliente',
            name='origem_lead',
            field=models.CharField(blank=True, choices=[('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('GOOGLE', 'Google'), ('SITE', 'Site'), ('WHATSAPP', 'WhatsApp'), ('INDICACAO', 'Indicação'), ('REPRESENTANTE', 'Representante'), ('CLIENTE_ANTIGO', 'Cliente Antigo'), ('TELEMARKETING', 'Telemarketing'), ('FEIRA', 'Feira'), ('PESQUISA', 'Pesquisa'), ('OUTROS', 'Outros')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='regiao_atuacao',
            field=models.CharField(blank=True, choices=[('NORTE', 'Norte'), ('NORDESTE', 'Nordeste'), ('CENTRO_OESTE', 'Centro-Oeste'), ('SUDESTE', 'Sudeste'), ('SUL', 'Sul')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='segmento',
            field=models.CharField(blank=True, choices=[('MOVEIS', 'Móveis'), ('ESTOFADOS', 'Estofados'), ('VAREJO', 'Varejo'), ('ALTO_PADRAO', 'Alto Padrão'), ('DECORACAO', 'Decoração'), ('PLANEJADOS', 'Planejados'), ('CORPORATIVO', 'Corporativo'), ('HOTELARIA', 'Hotelaria'), ('E_COMMERCE', 'E-commerce'), ('OUTROS', 'Outros')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='status_funil',
            field=models.CharField(choices=[('LEAD_NOVO', 'Lead Novo'), ('EM_CONTATO', 'Em Contato'), ('PROPOSTA_ENVIADA', 'Proposta Enviada'), ('NEGOCIACAO', 'Negociação'), ('AGUARDANDO_RETORNO', 'Aguardando Retorno'), ('PEDIDO_FECHADO', 'Pedido Fechado'), ('CLIENTE_ATIVO', 'Cliente Ativo'), ('CLIENTE_PERDIDO', 'Cliente Perdido')], default='LEAD_NOVO', max_length=30),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(blank=True, choices=[('LOJA_MOVEIS', 'Loja de Móveis'), ('ARQUITETO', 'Arquiteto'), ('DESIGNER_INTERIORES', 'Designer de Interiores'), ('REVENDA', 'Revenda'), ('MARKETPLACE', 'Marketplace'), ('HOTELARIA', 'Hotelaria'), ('CORPORATIVO', 'Corporativo'), ('CONSUMIDOR_FINAL', 'Consumidor Final'), ('OUTROS', 'Outros')], max_length=30, null=True),
        ),
        migrations.RunPython(normalizar_instagram_existente, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cliente',
            name='instagram',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
