# Generated by Django 5.2.15 on 2026-06-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_cep_cliente_origem_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='modalidade_cliente',
            field=models.CharField(blank=True, choices=[('RECORRENTE', 'Recorrente'), ('COMPRA_UNICA', 'Compra Única')], max_length=20, null=True, verbose_name='Tipo Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(blank=True, choices=[('LOJA_MOVEIS', 'Loja de Móveis'), ('ARQUITETO', 'Arquiteto'), ('DESIGNER_INTERIORES', 'Designer de Interiores'), ('REVENDA', 'Revenda'), ('MARKETPLACE', 'Marketplace'), ('HOTELARIA', 'Hotelaria'), ('CORPORATIVO', 'Corporativo'), ('CONSUMIDOR_FINAL', 'Consumidor Final'), ('OUTROS', 'Outros')], max_length=30, null=True, verbose_name='Perfil do Cliente'),
        ),
    ]
