# Generated by Django 5.2.15 on 2026-06-16 11:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def migrar_inativos_e_produtos(apps, schema_editor):
    Cliente = apps.get_model('clientes', 'Cliente')
    Produto = apps.get_model('clientes', 'Produto')
    ClienteProduto = apps.get_model('clientes', 'ClienteProduto')

    Cliente.objects.filter(ativo_no_sistema=False).update(categoria='inativo')

    produtos_exclusivos_ids = set()
    for cliente in Cliente.objects.all():
        for produto in cliente.produtos_exclusivos.all():
            produtos_exclusivos_ids.add(produto.pk)
            ClienteProduto.objects.get_or_create(
                cliente_id=cliente.pk,
                produto_id=produto.pk,
            )

    Produto.objects.filter(novo=True).update(tipo_produto='EXCLUSIVO')
    if produtos_exclusivos_ids:
        Produto.objects.filter(pk__in=produtos_exclusivos_ids).update(tipo_produto='EXCLUSIVO')


def reverse_migrar(apps, schema_editor):
    Cliente = apps.get_model('clientes', 'Cliente')
    ClienteProduto = apps.get_model('clientes', 'ClienteProduto')

    for cliente in Cliente.objects.filter(categoria='inativo'):
        cliente.ativo_no_sistema = False
        cliente.save(update_fields=['ativo_no_sistema'])

    for vinculo in ClienteProduto.objects.select_related('cliente', 'produto'):
        vinculo.cliente.produtos_exclusivos.add(vinculo.produto)


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_modalidade_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='categoria',
            field=models.CharField(
                choices=[
                    ('ativo', 'Ativo'),
                    ('adormecido', 'Adormecido'),
                    ('prospeccao', 'Prospecção'),
                    ('inativo', 'Inativo'),
                ],
                default='ativo',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo_produto',
            field=models.CharField(
                choices=[
                    ('PADRAO', 'Padrão'),
                    ('EXCLUSIVO', 'Exclusivo'),
                    ('UNICO', 'Único'),
                ],
                default='PADRAO',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='ProdutoExclusividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(blank=True, choices=[('NORTE', 'Norte'), ('NORDESTE', 'Nordeste'), ('CENTRO_OESTE', 'Centro-Oeste'), ('SUDESTE', 'Sudeste'), ('SUL', 'Sul')], max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusividades', to='clientes.produto')),
            ],
            options={
                'verbose_name': 'exclusividade de produto',
                'verbose_name_plural': 'exclusividades de produto',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ClienteProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_produto', to='clientes.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_cliente', to='clientes.produto')),
            ],
            options={
                'verbose_name': 'vínculo cliente-produto',
                'verbose_name_plural': 'vínculos cliente-produto',
                'ordering': ['-data_inicio'],
                'unique_together': {('cliente', 'produto')},
            },
        ),
        migrations.RunPython(migrar_inativos_e_produtos, reverse_migrar),
        migrations.RemoveField(
            model_name='cliente',
            name='ativo_no_sistema',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='produtos_exclusivos',
        ),
    ]
