# Generated by Django 6.0.6 on 2026-06-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_multiusuario_fase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='motivo_perda',
            field=models.CharField(blank=True, choices=[('PRECO', 'Preço'), ('PRAZO', 'Prazo'), ('CONCORRENTE', 'Concorrente'), ('SEM_RETORNO', 'Sem retorno'), ('PRODUTO_INADEQUADO', 'Produto inadequado'), ('OUTRO', 'Outro')], max_length=30),
        ),
        migrations.AddField(
            model_name='cliente',
            name='motivo_perda_detalhe',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
