# Generated by Django 6.0.6 on 2026-06-25 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(db_index=True, max_length=16)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'token da extensão',
                'verbose_name_plural': 'tokens da extensão',
                'ordering': ['-criado_em'],
            },
        ),
    ]
